# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hold_pb2 as hold__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hold_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HoldStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/hold.Hold/GetInfo',
                request_serializer=hold__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=hold__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.Invoice = channel.unary_unary(
                '/hold.Hold/Invoice',
                request_serializer=hold__pb2.InvoiceRequest.SerializeToString,
                response_deserializer=hold__pb2.InvoiceResponse.FromString,
                _registered_method=True)
        self.Inject = channel.unary_unary(
                '/hold.Hold/Inject',
                request_serializer=hold__pb2.InjectRequest.SerializeToString,
                response_deserializer=hold__pb2.InjectResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/hold.Hold/List',
                request_serializer=hold__pb2.ListRequest.SerializeToString,
                response_deserializer=hold__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Settle = channel.unary_unary(
                '/hold.Hold/Settle',
                request_serializer=hold__pb2.SettleRequest.SerializeToString,
                response_deserializer=hold__pb2.SettleResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/hold.Hold/Cancel',
                request_serializer=hold__pb2.CancelRequest.SerializeToString,
                response_deserializer=hold__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Clean = channel.unary_unary(
                '/hold.Hold/Clean',
                request_serializer=hold__pb2.CleanRequest.SerializeToString,
                response_deserializer=hold__pb2.CleanResponse.FromString,
                _registered_method=True)
        self.Track = channel.unary_stream(
                '/hold.Hold/Track',
                request_serializer=hold__pb2.TrackRequest.SerializeToString,
                response_deserializer=hold__pb2.TrackResponse.FromString,
                _registered_method=True)
        self.TrackAll = channel.unary_stream(
                '/hold.Hold/TrackAll',
                request_serializer=hold__pb2.TrackAllRequest.SerializeToString,
                response_deserializer=hold__pb2.TrackAllResponse.FromString,
                _registered_method=True)
        self.OnionMessages = channel.stream_stream(
                '/hold.Hold/OnionMessages',
                request_serializer=hold__pb2.OnionMessageResponse.SerializeToString,
                response_deserializer=hold__pb2.OnionMessage.FromString,
                _registered_method=True)


class HoldServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Settle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clean(self, request, context):
        """Cleans cancelled invoices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Track(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnionMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HoldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=hold__pb2.GetInfoRequest.FromString,
                    response_serializer=hold__pb2.GetInfoResponse.SerializeToString,
            ),
            'Invoice': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoice,
                    request_deserializer=hold__pb2.InvoiceRequest.FromString,
                    response_serializer=hold__pb2.InvoiceResponse.SerializeToString,
            ),
            'Inject': grpc.unary_unary_rpc_method_handler(
                    servicer.Inject,
                    request_deserializer=hold__pb2.InjectRequest.FromString,
                    response_serializer=hold__pb2.InjectResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hold__pb2.ListRequest.FromString,
                    response_serializer=hold__pb2.ListResponse.SerializeToString,
            ),
            'Settle': grpc.unary_unary_rpc_method_handler(
                    servicer.Settle,
                    request_deserializer=hold__pb2.SettleRequest.FromString,
                    response_serializer=hold__pb2.SettleResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=hold__pb2.CancelRequest.FromString,
                    response_serializer=hold__pb2.CancelResponse.SerializeToString,
            ),
            'Clean': grpc.unary_unary_rpc_method_handler(
                    servicer.Clean,
                    request_deserializer=hold__pb2.CleanRequest.FromString,
                    response_serializer=hold__pb2.CleanResponse.SerializeToString,
            ),
            'Track': grpc.unary_stream_rpc_method_handler(
                    servicer.Track,
                    request_deserializer=hold__pb2.TrackRequest.FromString,
                    response_serializer=hold__pb2.TrackResponse.SerializeToString,
            ),
            'TrackAll': grpc.unary_stream_rpc_method_handler(
                    servicer.TrackAll,
                    request_deserializer=hold__pb2.TrackAllRequest.FromString,
                    response_serializer=hold__pb2.TrackAllResponse.SerializeToString,
            ),
            'OnionMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.OnionMessages,
                    request_deserializer=hold__pb2.OnionMessageResponse.FromString,
                    response_serializer=hold__pb2.OnionMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hold.Hold', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hold.Hold', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hold:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/GetInfo',
            hold__pb2.GetInfoRequest.SerializeToString,
            hold__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/Invoice',
            hold__pb2.InvoiceRequest.SerializeToString,
            hold__pb2.InvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/Inject',
            hold__pb2.InjectRequest.SerializeToString,
            hold__pb2.InjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/List',
            hold__pb2.ListRequest.SerializeToString,
            hold__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Settle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/Settle',
            hold__pb2.SettleRequest.SerializeToString,
            hold__pb2.SettleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/Cancel',
            hold__pb2.CancelRequest.SerializeToString,
            hold__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hold.Hold/Clean',
            hold__pb2.CleanRequest.SerializeToString,
            hold__pb2.CleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Track(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hold.Hold/Track',
            hold__pb2.TrackRequest.SerializeToString,
            hold__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hold.Hold/TrackAll',
            hold__pb2.TrackAllRequest.SerializeToString,
            hold__pb2.TrackAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnionMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hold.Hold/OnionMessages',
            hold__pb2.OnionMessageResponse.SerializeToString,
            hold__pb2.OnionMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
